# Generated by Django 5.2.17 on 2026-08-25 06:22

import apps.core.utils
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.CharField(default=apps.core.utils.generate_activity_log_id, max_length=128, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, db_column='user_id', max_length=128, null=True)),
                ('user_name', models.CharField(db_column='user_name', max_length=255)),
                ('user_avatar', models.TextField(blank=True, db_column='user_avatar', null=True)),
                ('action', models.CharField(db_column='action', max_length=64)),
                ('target_type', models.CharField(db_column='target_type', max_length=64)),
                ('target_id', models.CharField(blank=True, db_column='target_id', max_length=128, null=True)),
                ('target_title', models.CharField(blank=True, db_column='target_title', max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, db_column='ip_address', max_length=64, null=True)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
