import { Category, SiteSettings, Tag, User } from '../types';

export const DEFAULT_PRIVACY_POLICY_CONFIG = {
  title: 'Privacy Policy',
  intro: 'At Naya Andaaz, your privacy is important to us. This Privacy Policy explains how we collect, use, disclose and protect your information when you visit our website and use our services.',
  sections: [
    {
      id: 'sec_1',
      number: '1',
      icon: 'User',
      heading: 'Information We Collect',
      description: 'We collect information you provide directly to us and certain information automatically when you visit our website.',
    },
    {
      id: 'sec_2',
      number: '2',
      icon: 'BarChart3',
      heading: 'How We Use Your Information',
      description: 'We use the information we collect to provide, improve, personalize and enhance your experience on our website.',
    },
    {
      id: 'sec_3',
      number: '3',
      icon: 'Share2',
      heading: 'How We Share Your Information',
      description: 'We do not sell or rent your personal information. We may share it with trusted third-party service providers under strict obligations.',
    },
    {
      id: 'sec_4',
      number: '4',
      icon: 'ShieldCheck',
      heading: 'Cookies and Tracking Technologies',
      description: 'We use cookies and similar technologies to enhance your browsing experience and analyze website traffic.',
    },
    {
      id: 'sec_5',
      number: '5',
      icon: 'Mail',
      heading: 'Newsletter Subscription',
      description: 'If you subscribe to our newsletter, we will use your email address to send you updates, stories and offers.',
    },
    {
      id: 'sec_6',
      number: '6',
      icon: 'Lock',
      heading: 'Data Security',
      description: 'We implement reasonable security measures to protect your information from unauthorized access, alteration or disclosure.',
    },
    {
      id: 'sec_7',
      number: '7',
      icon: 'User',
      heading: 'Your Rights and Choices',
      description: 'You have the right to access, update or delete your personal information and opt out of marketing communications.',
    },
    {
      id: 'sec_8',
      number: '8',
      icon: 'FileText',
      heading: 'Children\'s Privacy',
      description: 'Our website is not intended for children under the age of 13. We do not knowingly collect personal information from children.',
    },
    {
      id: 'sec_9',
      number: '9',
      icon: 'Globe',
      heading: 'Third-Party Links',
      description: 'Our website may contain links to third-party websites. We are not responsible for their privacy practices or content.',
    },
    {
      id: 'sec_10',
      number: '10',
      icon: 'Edit3',
      heading: 'Changes to This Privacy Policy',
      description: 'We may update this Privacy Policy from time to time. Any updates will be posted on this page with the revised “Last Updated” date.',
    },
  ],
  contact: {
    number: '11',
    icon: 'Mail',
    heading: 'Contact Us',
    description: 'If you have any questions, concerns or requests regarding this Privacy Policy or our data practices, please contact us.',
    email: 'hello@nayaandaaz.com',
    website: 'www.nayaandaaz.com',
    address: 'Naya Andaaz Digital Media, India',
  },
};

export const DEFAULT_ABOUT_US_CONFIG = {
  heroTitle: 'About Us',
  heroDescription: 'Naya Andaaz is an independent digital magazine that celebrates modern Indian lifestyle in all its colours. We bring you stories that inform, inspire and empower you to live your best life, every day.',
  aboutSection: {
    title: 'About Naya Andaaz',
    description: 'Naya Andaaz is an independent digital lifestyle magazine dedicated to bringing readers fresh, engaging and inspiring stories from the world of contemporary living. We cover the latest trends, ideas and conversations across fashion, beauty, entertainment, food, travel, wellness, astrology, relationships, career and finance.\n\nOur goal is to make lifestyle content informative, relatable and enjoyable while reflecting the changing interests and aspirations of today\'s readers.',
  },
  whatWeCover: {
    title: 'What We Cover',
    categories: [
      { id: 'cat_1', name: 'Fashion & Style', icon: 'Shirt' },
      { id: 'cat_2', name: 'Beauty & Wellness', icon: 'Heart' },
      { id: 'cat_3', name: 'Celebrity & Entertainment', icon: 'Star' },
      { id: 'cat_4', name: 'Food & Recipes', icon: 'Utensils' },
      { id: 'cat_5', name: 'Travel & Destinations', icon: 'Plane' },
      { id: 'cat_6', name: 'Relationships & Lifestyle', icon: 'Users' },
      { id: 'cat_7', name: 'Astrology', icon: 'Sparkles' },
      { id: 'cat_8', name: 'Career & Finance', icon: 'Briefcase' },
    ],
  },
  mission: {
    title: 'Our Mission',
    description: 'Our mission is to create meaningful and engaging lifestyle content that informs, inspires and helps readers discover something new. We aim to combine timely trends with useful insights, presenting stories in a simple, accessible and engaging way.\n\nWe believe lifestyle journalism should not only follow trends but also help readers understand the ideas, people and culture behind them.',
  },
  editorialApproach: {
    title: 'Our Editorial Approach',
    description: 'At Naya Andaaz, we value accuracy, originality and responsible storytelling. Our content is created with a focus on providing useful information while keeping the reader experience at the centre.',
    bulletPoints: [
      'We aim for accurate and reliable information.',
      'We focus on original and useful storytelling.',
      'We clearly distinguish facts, opinions and editorial perspectives.',
      'We update information when important details change.',
      'We strive to maintain a respectful and responsible editorial standard.',
    ],
  },
  whyNayaAndaaz: {
    title: 'Why Naya Andaaz?',
    paragraphs: [
      'Naya Andaaz brings together fashion, entertainment, lifestyle, culture and everyday inspiration in one digital destination. Whether you are looking for the latest fashion trends, celebrity updates, travel ideas, wellness inspiration or stories about modern relationships and careers, our aim is to make discovery easy and enjoyable.',
      'The name Naya Andaaz, meaning a new style or fresh perspective, reflects our approach to modern lifestyle journalism.',
    ],
  },
  readers: {
    title: 'Our Readers',
    description: 'Naya Andaaz is created for readers who enjoy discovering new trends, ideas, experiences and perspectives. Our content is designed for anyone interested in modern Indian lifestyle and the changing world of fashion, entertainment, culture and everyday living.',
  },
  commitment: {
    title: 'Our Commitment to Readers',
    description: 'Our readers are at the heart of everything we publish. We are committed to continuously improving the quality of our content and creating a publication that readers can return to for inspiration, information and entertainment.',
    subDescription: 'If you notice an error, have a suggestion or believe a piece of information needs to be corrected, we welcome your feedback.',
  },
  contact: {
    title: 'Contact Us',
    description: 'For editorial questions, corrections, feedback, partnerships or other enquiries, please get in touch with the Naya Andaaz team. We would love to hear from you!',
    buttonText: 'CONTACT US',
    buttonUrl: '#contact',
  },
};

export const DEFAULT_SITE_SETTINGS: SiteSettings = {
  siteName: 'Naya Andaaz',
  siteDescription: 'Naya Andaaz brings you the latest news, stories and updates on entertainment, lifestyle, fashion, travel, food, wellness, relationships and more.',
  siteUrl: 'https://www.nayaandaaz.com',
  logo: '/logo.svg',
  logo_url: '',
  logoPrimary: '',
  logoMobile: '',
  logoFooter: '',
  footer_logo_url: '',
  favicon: '/favicon.ico',
  postsPerPage: 10,
  trendingTickerText: 'BREAKING: Global Fashion Week unveils sustainable forward trends • Venice Film Festival announcements • Tech innovations for 2026',
  defaultSeoTitle: 'Naya Andaaz — News, Magazine & Contemporary Lifestyle',
  defaultMetaDescription: 'Naya Andaaz brings you the latest news, stories and updates on entertainment, lifestyle, fashion, travel, food, wellness, relationships and more.',
  defaultOgImage: 'https://res.cloudinary.com/adstnwn7/image/upload/f_auto,q_auto/v1/sereia_cms/1000064066_1788093083041?_a=BAMAAAcg0',
  googleAnalyticsId: 'G-NAYAANDAAZ2026',
  // Social links
  socialLinks: [
    { id: 'soc_fb', platform: 'facebook', label: 'Facebook', url: 'https://facebook.com/nayaandaazmagazine', isEnabled: true, order: 0 },
    { id: 'soc_ig', platform: 'instagram', label: 'Instagram', url: 'https://instagram.com/nayaandaazmag', isEnabled: true, order: 1 },
    { id: 'soc_tw', platform: 'twitter', label: 'X (Twitter)', url: 'https://twitter.com/nayaandaaznews', isEnabled: true, order: 2 },
    { id: 'soc_yt', platform: 'youtube', label: 'YouTube', url: 'https://youtube.com/@nayaandaazmagazine', isEnabled: true, order: 3 },
    { id: 'soc_pin', platform: 'pinterest', label: 'Pinterest', url: 'https://pinterest.com/nayaandaaz', isEnabled: false, order: 4 },
    { id: 'soc_li', platform: 'linkedin', label: 'LinkedIn', url: 'https://linkedin.com/company/nayaandaaz', isEnabled: false, order: 5 },
  ],
  facebookUrl: 'https://facebook.com/nayaandaazmagazine',
  twitterUrl: 'https://twitter.com/nayaandaaznews',
  instagramUrl: 'https://instagram.com/nayaandaazmag',
  youtubeUrl: 'https://youtube.com/@nayaandaazmagazine',
  pinterestUrl: 'https://pinterest.com/nayaandaaz',
  linkedinUrl: 'https://linkedin.com/company/nayaandaaz',
  enableAds: true,
  headerAdHtml: '<div class="w-full h-full bg-stone-100 flex items-center justify-center text-xs font-mono text-stone-400 border border-stone-200">RESPONSIVE LEADERBOARD AD BANNER (728x90 / 300x100)</div>',
  sidebarAdHtml: '<div class="w-full h-64 bg-stone-100 flex items-center justify-center text-xs font-mono text-stone-400 border border-stone-200">SPONSORED MEDIUM RECTANGLE (300x250)</div>',
  inArticleAdHtml: '<div class="w-full my-6 p-4 bg-stone-50 border border-stone-200 rounded text-center text-xs font-mono text-stone-400">IN-ARTICLE ADVERTISEMENT</div>',
  contactEmail: 'hello@nayaandaaz.com',
  copyrightText: `© ${new Date().getFullYear()} Naya Andaaz Media Group. All rights reserved.`,
  aboutUs: DEFAULT_ABOUT_US_CONFIG,
  privacy_policy_page: DEFAULT_PRIVACY_POLICY_CONFIG,
};

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_admin_01',
    name: 'Naya Andaaz',
    username: 'nayaandaaz',
    email: 'admin@nayaandaaz.com',
    passwordHash: '$2b$10$4IL0ixunhVNHSf9rfPmTteI8gXw5MvKqil4Z2gafJ5oAAZVd8vLP2', // AdminPass2026!
    role: 'admin',
    avatar: 'https://gravatar.com/avatar/dcdcdbf3d0fc135bdcff62f13818338ddf575b28e71fed69daab2309d1da252a?v=1788312978000&size=256&d=initials',
    bio: 'Editor-in-Chief & Founder of Naya Andaaz. Over 14 years covering international fashion, modern culture, and editorial strategy.',
    website: 'https://elenarostova.com',
    twitter: 'elenarostova',
    instagram: 'elena_rostova',
    isActive: true,
    emailVerified: true,
    postsCount: 14,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-08-01T12:00:00Z',
  },
  {
    id: 'usr_editor_02',
    name: 'Marcus Vance',
    username: 'marcus.vance',
    email: 'editor@nayaandaaz.news',
    passwordHash: '$2b$10$4IL0ixunhVNHSf9rfPmTteI8gXw5MvKqil4Z2gafJ5oAAZVd8vLP2', // AdminPass2026!
    role: 'editor',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    bio: 'Senior Cultural Critic & Lifestyle Editor. Passionate about cinematic retrospectives, architecture, and contemporary gastronomy.',
    website: 'https://marcusvance.com',
    twitter: 'marcusvance',
    isActive: true,
    emailVerified: true,
    postsCount: 8,
    createdAt: '2026-01-15T09:30:00Z',
    updatedAt: '2026-08-02T10:00:00Z',
  },
  {
    id: 'usr_author_03',
    name: 'Aria Sterling',
    username: 'aria.sterling',
    email: 'author@nayaandaaz.news',
    passwordHash: '$2b$10$4IL0ixunhVNHSf9rfPmTteI8gXw5MvKqil4Z2gafJ5oAAZVd8vLP2', // AdminPass2026!
    role: 'author',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
    bio: 'Fashion Feature Writer and Trend Analyst exploring the intersection of couture aesthetics, mindful living, and sustainable design.',
    twitter: 'ariasterling',
    instagram: 'aria_sterling',
    isActive: true,
    emailVerified: true,
    postsCount: 6,
    createdAt: '2026-02-01T11:00:00Z',
    updatedAt: '2026-07-28T14:20:00Z',
  },
  {
    id: 'usr_subscriber_04',
    name: 'Julian Hayes',
    username: 'julian.hayes',
    email: 'user@nayaandaaz.news',
    passwordHash: '$2b$10$4IL0ixunhVNHSf9rfPmTteI8gXw5MvKqil4Z2gafJ5oAAZVd8vLP2', // AdminPass2026!
    role: 'subscriber',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=200&q=80',
    bio: 'Avid reader, lifestyle enthusiast, and architecture aficionado.',
    isActive: true,
    emailVerified: true,
    postsCount: 0,
    createdAt: '2026-03-10T14:00:00Z',
    updatedAt: '2026-06-15T09:00:00Z',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat_entertainment',
    name: 'Entertainment',
    slug: 'entertainment',
    description: 'Cinema, streaming exclusives, celebrity profiles, and industry spotlights.',
    seoTitle: 'Entertainment: Movies, OTT & Celebrity News | Naya Andaaz',
    metaDescription: 'Explore the latest entertainment stories, Bollywood, Hollywood, OTT releases, movie reviews, and celebrity features on Naya Andaaz.',
    color: '#E11D48', // rose
    order: 1,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_ent_movies',
    name: 'Movies News & Updates',
    slug: 'movies-news',
    parentId: 'cat_entertainment',
    parentName: 'Entertainment',
    description: 'Box office revelations, festival debuts, and directorial interviews.',
    seoTitle: 'Movies News & Updates | Entertainment | Naya Andaaz',
    metaDescription: 'Latest movie news, trailers, box office updates, and film releases on Naya Andaaz.',
    color: '#E11D48',
    order: 1,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_ent_tv',
    name: 'Television & OTT',
    slug: 'television-ott',
    parentId: 'cat_entertainment',
    parentName: 'Entertainment',
    description: 'Binge-worthy series recaps, season premieres, and streaming forecasts.',
    seoTitle: 'Television & OTT Shows: Reviews, News & Recaps | Naya Andaaz',
    metaDescription: 'Discover the best OTT series, TV show recaps, streaming recommendations, and cast interviews on Naya Andaaz.',
    color: '#E11D48',
    order: 2,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_ent_celeb',
    name: 'Celebrities',
    slug: 'celebrities',
    parentId: 'cat_entertainment',
    parentName: 'Entertainment',
    description: 'Candid portraits, red carpet glamour, and cultural icons.',
    seoTitle: 'Celebrity News, Red Carpet & Gossip | Naya Andaaz',
    metaDescription: 'Catch up on celebrity news, exclusive interviews, red carpet style, and personal updates on Naya Andaaz.',
    color: '#E11D48',
    order: 3,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_lifestyle',
    name: 'Women & Lifestyle',
    slug: 'women-lifestyle',
    description: 'Empowering narratives, holistic wellbeing, and modern living chronicles.',
    seoTitle: 'Women & Lifestyle: Trends, Wellness, Career & More',
    metaDescription: 'Explore inspiring women and lifestyle stories covering beauty, fashion, wellness, career, relationships, culture and everyday life.',
    color: '#8B5CF6', // purple
    order: 2,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_society',
    name: 'Society & Culture',
    slug: 'society-culture',
    parentId: 'cat_lifestyle',
    parentName: 'Women & Lifestyle',
    description: 'Thoughtful essays on modern sociological shifts, human connection, and artistic movements.',
    seoTitle: 'Society & Culture: Modern Perspectives & Essays | Naya Andaaz',
    metaDescription: 'Read thoughtful essays on culture, community, sociological trends, and modern heritage on Naya Andaaz.',
    color: '#6366F1', // indigo
    order: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_style',
    name: 'Style & Fashion',
    slug: 'style',
    parentId: 'cat_lifestyle',
    parentName: 'Women & Lifestyle',
    description: 'Runway trends, seasonal wardrobe essentials, and haute couture retrospectives.',
    seoTitle: 'Style & Fashion: Runway Trends & Wardrobe Inspiration | Naya Andaaz',
    metaDescription: 'Discover the latest fashion trends, runway highlights, style tips, and capsule wardrobe advice on Naya Andaaz.',
    color: '#EC4899', // pink
    order: 1,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_beauty',
    name: 'Beauty',
    slug: 'beauty',
    parentId: 'cat_lifestyle',
    parentName: 'Women & Lifestyle',
    description: 'Skincare rituals, editorial cosmetics, and clean beauty philosophies.',
    seoTitle: 'Beauty: Skincare, Makeup Trends & Clean Formulations | Naya Andaaz',
    metaDescription: 'Expert beauty tips, dermatologist insights, trending makeup tutorials, and skincare routines on Naya Andaaz.',
    color: '#F43F5E',
    order: 2,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_wellness',
    name: 'Wellness',
    slug: 'wellness',
    parentId: 'cat_lifestyle',
    parentName: 'Women & Lifestyle',
    description: 'Mindful practices, longevity science, and restorative health routines.',
    seoTitle: 'Wellness: Mindful Living, Nutrition & Self-Care | Naya Andaaz',
    metaDescription: 'Holistic health guidance, meditation tips, nutrition advice, and mental wellbeing habits on Naya Andaaz.',
    color: '#10B981', // emerald
    order: 3,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_relationship',
    name: 'Relationship',
    slug: 'relationship',
    parentId: 'cat_lifestyle',
    parentName: 'Women & Lifestyle',
    description: 'Modern dating, communication clarity, and meaningful human connections.',
    seoTitle: 'Relationships & Modern Dating Advice | Naya Andaaz',
    metaDescription: 'Insights on love, emotional intelligence, modern relationships, and personal boundaries on Naya Andaaz.',
    color: '#F59E0B', // amber
    order: 4,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_travel',
    name: 'Travel & Escapes',
    slug: 'travel',
    description: 'Boutique destinations, secluded getaways, and immersive travel guides.',
    seoTitle: 'Travel & Escapes: Destination Guides & Boutique Getaways | Naya Andaaz',
    metaDescription: 'Immersive travel guides, boutique hotels, scenic itineraries, and cultural getaways curated by Naya Andaaz.',
    color: '#0EA5E9', // sky
    order: 3,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_food',
    name: 'Food & Wine',
    slug: 'food-wine',
    description: 'Culinary adventures, artisanal recipes, and Michelin dining narratives.',
    seoTitle: 'Food & Wine: Culinary Stories & Artisanal Recipes | Naya Andaaz',
    metaDescription: 'Epicurean journeys, seasonal recipes, wine pairings, and dining guides from top chefs on Naya Andaaz.',
    color: '#D97706', // amber
    order: 4,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_career',
    name: 'Career & Finance',
    slug: 'career-finance',
    description: 'Leadership insights, financial intelligence, and entrepreneurial mastery.',
    seoTitle: 'Career & Finance: Professional Growth & Wealth Management | Naya Andaaz',
    metaDescription: 'Actionable career advice, entrepreneurial strategies, investing fundamentals, and financial freedom tips on Naya Andaaz.',
    color: '#3B82F6', // blue
    order: 5,
    createdAt: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_TAGS: Tag[] = [
  { id: 'tag_1', name: 'Small Business', slug: 'small-business', description: 'Tips, strategies, and growth updates for emerging small businesses.', postCount: 14, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'tag_2', name: 'Street Food', slug: 'street-food', description: 'Exploring iconic roadside culinary cultures and authentic local flavours.', postCount: 18, createdAt: '2026-01-02T00:00:00Z' },
  { id: 'tag_3', name: 'Success Story', slug: 'success-story', description: 'Inspiring narratives of perseverance, entrepreneurship, and breakthroughs.', postCount: 22, createdAt: '2026-01-03T00:00:00Z' },
  { id: 'tag_4', name: 'Startup Story', slug: 'startup-story', description: 'Founding journeys, venture milestones, and modern enterprise innovations.', postCount: 16, createdAt: '2026-01-04T00:00:00Z' },
  { id: 'tag_5', name: 'Indian Food', slug: 'indian-food', description: 'Traditional recipes, regional delicacies, and spice heritage across India.', postCount: 25, createdAt: '2026-01-05T00:00:00Z' },
  { id: 'tag_6', name: 'Food Business', slug: 'food-business', description: 'Cloud kitchens, restaurant economics, and consumer dining trends.', postCount: 11, createdAt: '2026-01-06T00:00:00Z' },
  { id: 'tag_7', name: 'Dosa Business', slug: 'dosa-business', description: 'From humble street stalls to franchising South Indian culinary staples.', postCount: 9, createdAt: '2026-01-07T00:00:00Z' },
  { id: 'tag_8', name: 'Benne Dosa', slug: 'benne-dosa', description: 'Davanagere style butter dosas, crispy secrets, and heritage eateries.', postCount: 7, createdAt: '2026-01-08T00:00:00Z' },
  { id: 'tag_9', name: 'Mumbai News', slug: 'mumbai-news', description: 'Local developments, civic updates, and metro life in the City of Dreams.', postCount: 28, createdAt: '2026-01-09T00:00:00Z' },
  { id: 'tag_10', name: 'Entertainment News', slug: 'entertainment-news', description: 'Film releases, OTT premieres, celebrity interviews, and cultural buzz.', postCount: 34, createdAt: '2026-01-10T00:00:00Z' },
  { id: 'tag_11', name: 'Bollywood', slug: 'bollywood', description: 'Hindi cinema exclusives, box office reports, and industry spotlights.', postCount: 40, createdAt: '2026-01-11T00:00:00Z' },
  { id: 'tag_12', name: 'Cricket', slug: 'cricket', description: 'Match analyses, IPL updates, player profiles, and tournament schedules.', postCount: 31, createdAt: '2026-01-12T00:00:00Z' },
  { id: 'tag_13', name: 'Technology', slug: 'technology', description: 'Digital disruption, consumer gadgets, and frontier software developments.', postCount: 19, createdAt: '2026-01-13T00:00:00Z' },
  { id: 'tag_14', name: 'Lifestyle', slug: 'lifestyle', description: 'Wellness, modern living, home design, and personal growth.', postCount: 15, createdAt: '2026-01-14T00:00:00Z' },
];
