import { Category, SiteSettings, Tag, User } from '../types';

export const DEFAULT_PRIVACY_POLICY_CONFIG = {
  title: 'Privacy Policy',
  intro: 'At Sereia, accessible from https://sereia.com, your privacy is one of our top priorities. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website.',
  sections: [
    {
      id: 'sec_1',
      number: '1',
      icon: 'User',
      heading: 'Information We Collect',
      description: 'We may collect personal information that you voluntarily provide to us when you comment on articles, subscribe to our newsletter, or contact us.',
    },
    {
      id: 'sec_2',
      number: '2',
      icon: 'BarChart3',
      heading: 'How We Use Your Information',
      description: 'We use the information we collect to provide, operate, and maintain our website, improve our content and services, and communicate with you.',
    },
    {
      id: 'sec_3',
      number: '3',
      icon: 'ShieldCheck',
      heading: 'Cookies and Tracking Technologies',
      description: 'We use cookies and similar technologies to enhance your browsing experience, analyze site traffic, and understand user behavior. You can disable cookies in your browser.',
    },
    {
      id: 'sec_4',
      number: '4',
      icon: 'Share2',
      heading: 'Third-Party Services',
      description: 'We may use third-party services such as Google Analytics, AdSense, or social media plugins that may collect information about your activity on our website.',
    },
    {
      id: 'sec_5',
      number: '5',
      icon: 'Lock',
      heading: 'Data Security',
      description: 'We implement reasonable security measures to protect your information from unauthorized access, alteration, disclosure, or destruction.',
    },
    {
      id: 'sec_6',
      number: '6',
      icon: 'Mail',
      heading: 'Your Rights',
      description: 'You have the right to access, update, or delete your personal information. If you have any requests regarding your data, please contact us.',
    },
    {
      id: 'sec_7',
      number: '7',
      icon: 'FileText',
      heading: 'Children\'s Privacy',
      description: 'Our website is not intended for children under the age of 13. We do not knowingly collect personal information from children.',
    },
    {
      id: 'sec_8',
      number: '8',
      icon: 'Edit3',
      heading: 'Changes to This Policy',
      description: 'We may update this Privacy Policy from time to time. Any changes will be posted on this page with an updated revision date.',
    },
  ],
  contact: {
    number: '9',
    icon: 'PhoneCall',
    heading: 'Contact Us',
    description: 'If you have any questions about this Privacy Policy, please contact us at:',
    email: 'hello@sereia.com',
  },
};

export const DEFAULT_SITE_SETTINGS: SiteSettings = {
  siteName: 'Sereia',
  siteDescription: 'Premium News, Culture, Style & Modern Lifestyle Magazine',
  siteUrl: 'https://sereia.news',
  logo: '/logo.svg',
  favicon: '/favicon.ico',
  postsPerPage: 10,
  trendingTickerText: 'BREAKING: Global Fashion Week unveils sustainable forward trends • Venice Film Festival announcements • Tech innovations for 2026',
  defaultSeoTitle: 'Sereia — News, Magazine & Contemporary Lifestyle',
  defaultMetaDescription: 'The pulse of modern culture, entertainment, high fashion, wellness, career insights, and global lifestyle stories.',
  defaultOgImage: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=1200&q=80',
  googleAnalyticsId: 'G-SEREIA2026',
  facebookUrl: 'https://facebook.com/sereiamagazine',
  twitterUrl: 'https://twitter.com/sereianews',
  instagramUrl: 'https://instagram.com/sereiamag',
  youtubeUrl: 'https://youtube.com/@sereiamagazine',
  pinterestUrl: 'https://pinterest.com/sereia',
  linkedinUrl: 'https://linkedin.com/company/sereia',
  enableAds: true,
  headerAdHtml: '<div class="w-full h-full bg-stone-100 flex items-center justify-center text-xs font-mono text-stone-400 border border-stone-200">RESPONSIVE LEADERBOARD AD BANNER (728x90 / 300x100)</div>',
  sidebarAdHtml: '<div class="w-full h-64 bg-stone-100 flex items-center justify-center text-xs font-mono text-stone-400 border border-stone-200">SPONSORED MEDIUM RECTANGLE (300x250)</div>',
  inArticleAdHtml: '<div class="w-full my-6 p-4 bg-stone-50 border border-stone-200 rounded text-center text-xs font-mono text-stone-400">IN-ARTICLE ADVERTISEMENT</div>',
  contactEmail: 'contact@sereia.news',
  copyrightText: `© ${new Date().getFullYear()} Sereia Media Group. All rights reserved.`,
};

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_admin_01',
    name: 'Elena Rostova',
    username: 'elena.rostova',
    email: 'admin@sereia.news',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    bio: 'Editor-in-Chief & Founder of Sereia. Over 14 years covering international fashion, modern culture, and editorial strategy.',
    website: 'https://elenarostova.com',
    twitter: 'elenarostova',
    instagram: 'elena_rostova',
    isActive: true,
    postsCount: 14,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-08-01T12:00:00Z',
  },
  {
    id: 'usr_editor_02',
    name: 'Marcus Vance',
    username: 'marcus.vance',
    email: 'editor@sereia.news',
    role: 'editor',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    bio: 'Senior Cultural Critic & Lifestyle Editor. Passionate about cinematic retrospectives, architecture, and contemporary gastronomy.',
    website: 'https://marcusvance.com',
    twitter: 'marcusvance',
    isActive: true,
    postsCount: 8,
    createdAt: '2026-01-15T09:30:00Z',
    updatedAt: '2026-08-02T10:00:00Z',
  },
  {
    id: 'usr_author_03',
    name: 'Aria Sterling',
    username: 'aria.sterling',
    email: 'author@sereia.news',
    role: 'author',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
    bio: 'Fashion Feature Writer and Trend Analyst exploring the intersection of couture aesthetics, mindful living, and sustainable design.',
    twitter: 'ariasterling',
    instagram: 'aria_sterling',
    isActive: true,
    postsCount: 6,
    createdAt: '2026-02-01T11:00:00Z',
    updatedAt: '2026-07-28T14:20:00Z',
  },
  {
    id: 'usr_subscriber_04',
    name: 'Julian Hayes',
    username: 'julian.hayes',
    email: 'user@sereia.news',
    role: 'subscriber',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=200&q=80',
    bio: 'Avid reader, lifestyle enthusiast, and architecture aficionado.',
    isActive: true,
    postsCount: 0,
    createdAt: '2026-03-10T14:00:00Z',
    updatedAt: '2026-06-15T09:00:00Z',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat_entertainment',
    name: 'Entertainment',
    slug: 'entertainment',
    description: 'Cinema, streaming exclusives, celebrity profiles, and industry spotlights.',
    color: '#E11D48', // rose
    order: 1,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_ent_movies',
    name: 'Movies News & Updates',
    slug: 'movies-news',
    parentId: 'cat_entertainment',
    parentName: 'Entertainment',
    description: 'Box office revelations, festival debuts, and directorial interviews.',
    color: '#E11D48',
    order: 1,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_ent_tv',
    name: 'Television & OTT',
    slug: 'television-ott',
    parentId: 'cat_entertainment',
    parentName: 'Entertainment',
    description: 'Binge-worthy series recaps, season premieres, and streaming forecasts.',
    color: '#E11D48',
    order: 2,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_ent_celeb',
    name: 'Celebrities',
    slug: 'celebrities',
    parentId: 'cat_entertainment',
    parentName: 'Entertainment',
    description: 'Candid portraits, red carpet glamour, and cultural icons.',
    color: '#E11D48',
    order: 3,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_lifestyle',
    name: 'Women Lifestyle',
    slug: 'women-lifestyle',
    description: 'Empowering narratives, holistic wellbeing, and modern living chronicles.',
    color: '#8B5CF6', // purple
    order: 2,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_society',
    name: 'Society & Culture',
    slug: 'society-culture',
    parentId: 'cat_lifestyle',
    parentName: 'Women Lifestyle',
    description: 'Thoughtful essays on modern sociological shifts, human connection, and artistic movements.',
    color: '#6366F1', // indigo
    order: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_style',
    name: 'Style & Fashion',
    slug: 'style',
    parentId: 'cat_lifestyle',
    parentName: 'Women Lifestyle',
    description: 'Runway trends, seasonal wardrobe essentials, and haute couture retrospectives.',
    color: '#EC4899', // pink
    order: 1,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_beauty',
    name: 'Beauty',
    slug: 'beauty',
    parentId: 'cat_lifestyle',
    parentName: 'Women Lifestyle',
    description: 'Skincare rituals, editorial cosmetics, and clean beauty philosophies.',
    color: '#F43F5E',
    order: 2,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_wellness',
    name: 'Wellness',
    slug: 'wellness',
    parentId: 'cat_lifestyle',
    parentName: 'Women Lifestyle',
    description: 'Mindful practices, longevity science, and restorative health routines.',
    color: '#10B981', // emerald
    order: 3,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_relationship',
    name: 'Relationship',
    slug: 'relationship',
    parentId: 'cat_lifestyle',
    parentName: 'Women Lifestyle',
    description: 'Modern dating, communication clarity, and meaningful human connections.',
    color: '#F59E0B', // amber
    order: 4,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_travel',
    name: 'Travel & Escapes',
    slug: 'travel',
    description: 'Boutique destinations, secluded getaways, and immersive travel guides.',
    color: '#0EA5E9', // sky
    order: 3,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_food',
    name: 'Food & Wine',
    slug: 'food',
    description: 'Culinary adventures, artisanal recipes, and Michelin dining narratives.',
    color: '#D97706', // amber
    order: 4,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat_career',
    name: 'Career & Finance',
    slug: 'career-finance',
    description: 'Leadership insights, financial intelligence, and entrepreneurial mastery.',
    color: '#3B82F6', // blue
    order: 5,
    createdAt: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_TAGS: Tag[] = [
  { id: 'tag_1', name: 'Haute Couture', slug: 'haute-couture', postCount: 8, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'tag_2', name: 'Milan Fashion Week', slug: 'milan-fashion-week', postCount: 5, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'tag_3', name: 'Cinema 2026', slug: 'cinema-2026', postCount: 12, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'tag_4', name: 'Mindfulness', slug: 'mindfulness', postCount: 7, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'tag_5', name: 'Luxury Travel', slug: 'luxury-travel', postCount: 6, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'tag_6', name: 'Clean Beauty', slug: 'clean-beauty', postCount: 9, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'tag_7', name: 'Tech In Art', slug: 'tech-in-art', postCount: 4, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'tag_8', name: 'Fine Dining', slug: 'fine-dining', postCount: 5, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'tag_9', name: 'Leadership', slug: 'leadership', postCount: 3, createdAt: '2026-01-01T00:00:00Z' },
];
