# Generated by Django 5.2.17 on 2026-08-25 06:22

import apps.core.utils
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=apps.core.utils.generate_category_id, max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('meta_title', models.TextField(blank=True, db_column='meta_title', null=True)),
                ('meta_description', models.TextField(blank=True, db_column='meta_description', null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('canonical_url', models.TextField(blank=True, db_column='canonical_url', null=True)),
                ('og_image', models.TextField(blank=True, db_column='og_image', null=True)),
                ('twitter_image', models.TextField(blank=True, db_column='twitter_image', null=True)),
                ('display_order', models.IntegerField(db_column='display_order', default=0)),
                ('is_trashed', models.BooleanField(db_column='is_trashed', default=False)),
                ('trashed_at', models.DateTimeField(blank=True, db_column='trashed_at', null=True)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='categories.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
