# Generated by Django 5.2.17 on 2026-08-25 06:22

import apps.core.utils
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.CharField(default=apps.core.utils.generate_ad_id, max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(choices=[('header', 'Header Banner'), ('sidebar', 'Sidebar Sticky / Inline'), ('article_inline', 'Inside Article Content'), ('footer', 'Footer Banner'), ('popup', 'Pop-up / Interstitial')], max_length=64)),
                ('code', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, db_column='image_url', null=True)),
                ('target_url', models.TextField(blank=True, db_column='target_url', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, db_column='start_date', null=True)),
                ('end_date', models.DateTimeField(blank=True, db_column='end_date', null=True)),
                ('is_trashed', models.BooleanField(db_column='is_trashed', default=False)),
                ('trashed_at', models.DateTimeField(blank=True, db_column='trashed_at', null=True)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'db_table': 'advertisements',
                'ordering': ['-created_at'],
            },
        ),
    ]
