# Generated by Django 5.2.17 on 2026-08-25 06:22

import apps.core.utils
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=apps.core.utils.generate_comment_id, max_length=128, primary_key=True, serialize=False)),
                ('author_name', models.CharField(db_column='author_name', max_length=255)),
                ('author_email', models.CharField(db_column='author_email', max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending Moderation'), ('spam', 'Spam'), ('trash', 'Trash')], default='approved', max_length=32)),
                ('is_trashed', models.BooleanField(db_column='is_trashed', default=False)),
                ('trashed_at', models.DateTimeField(blank=True, db_column='trashed_at', null=True)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
